### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by kuqilin** [min0911Y/Plant-OS#1]
@min0911Y 

请问为什么不直接写一个统一的makefile将各文件夹下的源文件进行统一编译，而是要进入每一个文件夹进行`make`命令呢？实在不行可以写一个`bat`或者`sh`脚本文件进行各目录下的`make`呀。

以下代码或许可以进行参考（make.sh文件）

```bush
cd apps
make
cd ../Loader
make
cd ../kernel
make
```
之后，执行

```
chmod +x make.sh
```
为此文件添加可执行权限。

以后，执行`./make.sh`即可。

如有错误，请多指教，谢谢。

**Comment by copi143** [comment]
现在有build.sh了
