### ISSUE TITLE
[建议] 建议您添加对控制台虚拟终端序列的支持

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#10]
如题，控制台虚拟终端序列可以快速操作控制台文字格式。
您可以参阅：[https://learn.microsoft.com/zh-cn/windows/console/console-virtual-terminal-sequences](https://learn.microsoft.com/zh-cn/windows/console/console-virtual-terminal-sequences)

**Comment by min0911Y** [comment]
目前只有ANSI转义序列的计划在章程上
