### ISSUE TITLE
[建议] 使用动态链接库

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#13]
如题，我发现 Plant OS 的绝大多数程序都使用静态链接库，这样有几个缺点：

1.单个软件体积过大
1.对于适用于 Plant OS 的第三方软件，其静态链接的系统 API 可能与系统不适配（主要是因为版本问题）。

所以，我建议您使用动态链接库（像 Windows 系统的 DLL 一样）：
大概的方法是这样的：

* 对于系统库：将系统 API 编译成库，存储到文件中，并为该文件打上签名（如 MD5）
* 对于应用程序格式：在程序中添加导入段，用于存储动态链接库名（及签名）、函数名和指针
* 对于系统加载器：
  1.加载时依据导入段的动态链接库签名锁定需要使用的动态链接库
  2.加载动态链接库到内存中（如果是常用的库实际上可以在系统启动时就直接加载到内存中了）
  3.由导入段的函数名查找指定动态链接库中是否有函数，如果没有，报错退出
  4.将指定的函数指针写到导入段的指针区中
  5.启动程序
* 应用程序调用系统 API 时：
  1.切到导入段的指针区获取指定的指针（导入段的指针区可以直接在编译时就写死位置）
  2.依据获取到的指针调用系统 API

**Comment by min0911Y** [comment]
动态链接库在议程上，但不是现在

他不是使用不使用的问题 我现在还没找到一个合适的资料去写动态链接器

[建议]所有建议写一起，不要发很多条issue，这样不好

**Comment by ghost** [comment]
> 动态链接库在议程上，但不是现在
> 
> 他不是使用不使用的问题 我现在还没找到一个合适的资料去写动态链接器
> 
> [建议]所有建议写一起，不要发很多条issue，这样不好

试试《x86 汇编语言：从实模式到保护模式》”13.4 用户程序的加载和重定位“章节中的例子？
另：所有建议一起发怎么便于版本管理呢？

**Comment by min0911Y** [comment]
你发issue你肯定要所有一起发啊  你发的爽我邮件一直响

**Comment by ghost** [comment]
> 你发issue你肯定要所有一起发啊 你发的爽我邮件一直响

那您知道我在论坛上发一个小软件然后几十个 Bug 报上来的感受吗？

**Comment by min0911Y** [comment]
总好过邮件响几十次吧哥

**Comment by min0911Y** [comment]
你发一次发完 我一次回答完，方便你也方便我，人是有耐心的，我这边回答你，你那边又发一条，人是会烦的。

**Comment by min0911Y** [comment]
> > 动态链接库在议程上，但不是现在
> > 他不是使用不使用的问题 我现在还没找到一个合适的资料去写动态链接器
> > [建议]所有建议写一起，不要发很多条issue，这样不好
> 
> 试试《x86 汇编语言：从实模式到保护模式》”13.4 用户程序的加载和重定位“章节中的例子？ 另：所有建议一起发怎么便于版本管理呢？

另：版本管理和issue啥关系，你发pr肯定也是改了什么就一并发过去啊

如果你认为你说的有道理，请尝试这样给linux社区发issue

**Comment by ghost** [comment]
> > > 动态链接库在议程上，但不是现在
> > > 他不是使用不使用的问题 我现在还没找到一个合适的资料去写动态链接器
> > > [建议]所有建议写一起，不要发很多条issue，这样不好
> > 
> > 
> > 试试《x86 汇编语言：从实模式到保护模式》”13.4 用户程序的加载和重定位“章节中的例子？ 另：所有建议一起发怎么便于版本管理呢？
> 
> 另：版本管理和issue啥关系，你发pr肯定也是改了什么就一并发过去啊
> 
> 如果你认为你说的有道理，请尝试这样给linux社区发issue

您改完代码之后不在更新日志里面写修复了哪些问题的吗？

**Comment by min0911Y** [comment]
> > > > 动态链接库在议程上，但不是现在
> > > > 他不是使用不使用的问题 我现在还没找到一个合适的资料去写动态链接器
> > > > [建议]所有建议写一起，不要发很多条issue，这样不好
> > > 
> > > 
> > > 试试《x86 汇编语言：从实模式到保护模式》”13.4 用户程序的加载和重定位“章节中的例子？ 另：所有建议一起发怎么便于版本管理呢？
> > 
> > 
> > 另：版本管理和issue啥关系，你发pr肯定也是改了什么就一并发过去啊
> > 如果你认为你说的有道理，请尝试这样给linux社区发issue
> 
> 您改完代码之后不在更新日志里面写修复了哪些问题的吗？

这和你发issue有什么关系，你一条条说清楚我一样可以写更新日志

**Comment by min0911Y** [comment]
![image](https://github.com/min0911Y/Plant-OS/assets/86399932/e5f9237b-b755-4918-b8d5-494f231b2a6f)
有帮助，但不多，我现在想写的是使用.so文件的动态链接器，如果像这样搞的话，我也可以糊一个上去
