### ISSUE TITLE
[BUG]最新版本的 Plant OS 安装后无法正常启动

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#17]
如题，最新版本的 Plant OS 无法安装后无法正常启动，一个字也无法显示。
以启动盘启动再切入硬盘，输入 psh 只会显示红色的 "GP"

如图：
![屏幕截图 2024-04-14 165656](https://github.com/min0911Y/Plant-OS/assets/139534620/2b754dbb-037e-4734-ac32-a4a6e4aab6f4)

**Comment by min0911Y** [comment]
经测试正常启动，未能复现

**Comment by min0911Y** [comment]
成功复现 已fixed
