### ISSUE TITLE
[BUG]安装程序输出出错+无法正常启动

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#19]
状况如图：
1.安装程序输出出错，字符排版混乱
2.安装后从硬盘启动，但是启动之后Shell立马被系统杀进程了
编译平台：
WSL Ubuntu 22.04.3 LTS (GNU/Linux 5.15.146.1-microsoft-standard-WSL2 x86_64)
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
NASM version 2.15.05
附件里是我编译出来的bin
![屏幕截图 2024-04-20 111121](https://github.com/min0911Y/Plant-OS/assets/139534620/6a0064ff-34df-43fb-b6b9-6c66c4e1b555)
![屏幕截图 2024-04-20 111239](https://github.com/min0911Y/Plant-OS/assets/139534620/1424667c-f487-480e-a1ea-447e0ee06e67)
![屏幕截图 2024-04-20 113036](https://github.com/min0911Y/Plant-OS/assets/139534620/6097c432-aaf9-4f04-931d-22cc7932c442)
[nasm.zip](https://github.com/min0911Y/Plant-OS/files/15046853/nasm.zip)

**Comment by min0911Y** [comment]
使用你发送的镜像 未能复现

**Comment by min0911Y** [comment]
![Uploading 7890c7d7005600b52485e3b9baa085e5.png…]()

**Comment by min0911Y** [comment]
![7890c7d7005600b52485e3b9baa085e5](https://github.com/min0911Y/Plant-OS/assets/86399932/21a03bd5-68a0-48db-9e5f-a6f0d57660d6)

**Comment by ghost** [comment]
> ![7890c7d7005600b52485e3b9baa085e5](https://private-user-images.githubusercontent.com/86399932/324154438-21a03bd5-68a0-48db-9e5f-a6f0d57660d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1ODg4MDcsIm5iZiI6MTcxMzU4ODUwNywicGF0aCI6Ii84NjM5OTkzMi8zMjQxNTQ0MzgtMjFhMDNiZDUtNjhhMC00OGRiLTllNWYtYTZmMGQ1NzY2MGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA0NDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YjI4NGFiOTg1ZTViZWMyNmUyOWVmZDdmNzYwYTQ1OGRiMGNlZTIzNTNiODcyODkwZDAwYTg1YzQ3OWE1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_AnFoqZQk1ACyw5PXtjeu89vQAY5upHYiSiufeJf0s)

测试的平台不一样啊，我用的是 **VMware Workstation 17 Player** 的**非商业版本**

**Comment by ghost** [comment]
我反复测试了三次，分别采用了“MS-DOS”“其他”“其他（64位）”的设置，都是同样的结果啊

**Comment by min0911Y** [comment]
> > ![7890c7d7005600b52485e3b9baa085e5](https://private-user-images.githubusercontent.com/86399932/324154438-21a03bd5-68a0-48db-9e5f-a6f0d57660d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1ODg4MDcsIm5iZiI6MTcxMzU4ODUwNywicGF0aCI6Ii84NjM5OTkzMi8zMjQxNTQ0MzgtMjFhMDNiZDUtNjhhMC00OGRiLTllNWYtYTZmMGQ1NzY2MGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA0NDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YjI4NGFiOTg1ZTViZWMyNmUyOWVmZDdmNzYwYTQ1OGRiMGNlZTIzNTNiODcyODkwZDAwYTg1YzQ3OWE1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_AnFoqZQk1ACyw5PXtjeu89vQAY5upHYiSiufeJf0s)
> 
> 测试的平台不一样啊，我用的是 **VMware Workstation 17 Player** 的**非商业版本**

测试了同样的虚拟机 也无法复现

**Comment by min0911Y** [comment]
> 我反复测试了三次，分别采用了“MS-DOS”“其他”“其他（64位）”的设置，都是同样的结果啊

你的内存是多少

**Comment by ghost** [comment]
2GB

**Comment by min0911Y** [comment]
> 2GB

那就不明白了  但总之我这里是没问题的

我这里复现不出来也不好修

**Comment by min0911Y** [comment]
> 2GB

你用的是IDE还是AHCI

**Comment by ghost** [comment]
ahci

**Comment by min0911Y** [comment]
> ahci

那就很正常了 使用IDE测试 一定没问题

**Comment by min0911Y** [comment]
> ahci

忘记说了 AHCI有bug

**Comment by ghost** [comment]
What?

**Comment by min0911Y** [comment]
> What?

what what?

**Comment by ghost** [comment]
奇怪了，只安装系统本体但不安装第二、三张盘的程序以及资源盘的内容就能以硬盘正常启动

**Comment by min0911Y** [comment]
> 奇怪了，只安装系统本体但不安装第二、三张盘的程序以及资源盘的内容就能以硬盘正常启动

AHCI的话属于正常现象

**Comment by ghost** [comment]
……

**Comment by min0911Y** [comment]
> ……

总之 之后修AHCI 但不是现在

**Comment by ghost** [comment]
但是只用 IDE 的话安装好像也是同样的效果（现在我还在安装），而且速度实在太慢
![屏幕截图 2024-04-20 135023](https://github.com/min0911Y/Plant-OS/assets/139534620/e84a9c0e-d9ad-4ecb-bee7-27246a11ab6d)
