### ISSUE TITLE
[BUG及建议]安装程序输出出错+启动阶段有概率卡死+makefile更改建议

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#20]
**安装程序输出出错**
我在 #19 已经反馈过这个问题了，当时我以为仅仅是我的 Vmware 的问题，但是我在 qemu 上安装，安装程序的输出仍然惨不忍睹。
如图：
![屏幕截图 2024-05-01 103829](https://github.com/min0911Y/Plant-OS/assets/139534620/faf10654-a63d-4937-b1a2-3d958a1c62b3)

**启动阶段有概率卡死**
在 qemu 下，以安装盘启动时会卡死，以硬盘启动时目前还没有发现卡死情况。
卡死时，大多是在调用 0x2a908b
如：
```IN:
0x002aaa28:  call   0x2a908b
```

[11:43]另：
经多次测试发现，安装后只要访问硬盘，就有概率出错，如图：
![屏幕截图 2024-05-01 114319](https://github.com/min0911Y/Plant-OS/assets/139534620/dc696e14-d389-41b0-9314-9d4c75013dd0)

**makefile更改建议**
1.更改 `run` 部分
由
```makefile
run:
	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -device floppy -fda ./img/Powerint_DOS_386.img -drive id=disk,file=disk.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -hdb ./img/Disk2.img -hdc ./img/Disk3.img -hdd ./img/res.img -boot a -m 512
```
改为
```makefile
run:
	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -device floppy -fda ./img/Powerint_DOS_386.img -drive id=disk,file=disk.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -boot a -m 512
```
理由很简单，在qemu中可以用 change/eject 来换盘/弹出，且您的安装程序设计出来也不是从一个驱动器顺次读到最后一个驱动器的。
2.新增 `run_hd`
即硬盘启动
```makefile
run_hd:
	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -boot a -m 512
```

**Comment by min0911Y** [comment]
。。。。我是不是说过AHCI有bug 不要再用AHCI了


setup1是正常的 我的调试信息

**Comment by QZhiStudio** [comment]
> 。。。。我是不是说过AHCI有bug 不要再用AHCI了
> 
> setup1是正常的 我的调试信息

qemu您用的是 IDE 吗？

**Comment by ghost** [comment]
> 。。。。我是不是说过AHCI有bug 不要再用AHCI了
> 
> setup1是正常的 我的调试信息

在qemu下运行不是使用IDE吗？

**Comment by min0911Y** [comment]
> > 。。。。我是不是说过AHCI有bug 不要再用AHCI了
> > setup1是正常的 我的调试信息
> 
> 在qemu下运行不是使用IDE吗？

你给的代码
```make
run_hd:
	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -boot a -m 512
```
-device ahci 这不就是ahci吗

**Comment by ghost** [comment]
> > > 。。。。我是不是说过AHCI有bug 不要再用AHCI了
> > > setup1是正常的 我的调试信息
> > 
> > 
> > 在qemu下运行不是使用IDE吗？
> 
> 你给的代码
> 
> ```makefile
> run_hd:
> 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -boot a -m 512
> ```
> 
> -device ahci 这不就是ahci吗

makefile 改成这个样子了：
```makefile
run:
	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -device floppy -fda ./img/Powerint_DOS_386.img -drive id=disk,file=disk.img,if=none -device ide-hd,drive=disk -boot a -m 512
run_hd:
	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ide-hd,drive=disk -boot a -m 512
```
该卡还得卡
最主要的是要弄明白 0x2a908b 到底是什么函数

**Comment by min0911Y** [comment]
你这个访问磁盘是指读取啥的吗 我这没问题啊

**Comment by min0911Y** [comment]
> > > > 。。。。我是不是说过AHCI有bug 不要再用AHCI了
> > > > setup1是正常的 我的调试信息
> > > 
> > > 
> > > 在qemu下运行不是使用IDE吗？
> > 
> > 
> > 你给的代码
> > ```makefile
> > run_hd:
> > 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -boot a -m 512
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > -device ahci 这不就是ahci吗
> 
> makefile 改成这个样子了：
> 
> ```makefile
> run:
> 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -device floppy -fda ./img/Powerint_DOS_386.img -drive id=disk,file=disk.img,if=none -device ide-hd,drive=disk -boot a -m 512
> run_hd:
> 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ide-hd,drive=disk -boot a -m 512
> ```
> 
> 该卡还得卡 最主要的是要弄明白 0x2a908b 到底是什么函数

![image](https://github.com/min0911Y/Plant-OS/assets/86399932/605a9d32-e078-4377-a5a4-2dc056f0e5c1)
我不认为是这个函数

**Comment by min0911Y** [comment]
> > > > > 。。。。我是不是说过AHCI有bug 不要再用AHCI了
> > > > > setup1是正常的 我的调试信息
> > > > 
> > > > 
> > > > 在qemu下运行不是使用IDE吗？
> > > 
> > > 
> > > 你给的代码
> > > ```makefile
> > > run_hd:
> > > 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -boot a -m 512
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > -device ahci 这不就是ahci吗
> > 
> > 
> > makefile 改成这个样子了：
> > ```makefile
> > run:
> > 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -device floppy -fda ./img/Powerint_DOS_386.img -drive id=disk,file=disk.img,if=none -device ide-hd,drive=disk -boot a -m 512
> > run_hd:
> > 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ide-hd,drive=disk -boot a -m 512
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 该卡还得卡 最主要的是要弄明白 0x2a908b 到底是什么函数
> 
> ![image](https://private-user-images.githubusercontent.com/86399932/327065864-605a9d32-e078-4377-a5a4-2dc056f0e5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDU5NTIsIm5iZiI6MTcxNDU0NTY1MiwicGF0aCI6Ii84NjM5OTkzMi8zMjcwNjU4NjQtNjA1YTlkMzItZTA3OC00Mzc3LWE1YTQtMmRjMDU2ZjBlNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA2NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYTk2OGUwYjkzNzE0MjhlN2RmZDEyZWU2NmMyZmY1Njk5OTQ1NWZmNWNhNjhhZDgwY2ZiNTgzYWFlOWFhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y8FVkUSCZ3bxI37gfERaQdY1U8ZLNM62aqocYGk-T-I) 我不认为是这个函数

这个函数被调用 且只被调用一次

**Comment by min0911Y** [comment]
![image](https://github.com/min0911Y/Plant-OS/assets/86399932/d262ae73-5c68-4b1e-9eb6-2b01bd0d2ad8)
也许是这个问题 调用的应该是current_task

但并无理由current_task会出问题

**Comment by min0911Y** [comment]
附一张正常运行的图片
![image](https://github.com/min0911Y/Plant-OS/assets/86399932/6358b696-ca57-4f94-b429-84222bd7d755)

**Comment by ghost** [comment]
> > > > > > 。。。。我是不是说过AHCI有bug 不要再用AHCI了
> > > > > > setup1是正常的 我的调试信息
> > > > > 
> > > > > 
> > > > > 在qemu下运行不是使用IDE吗？
> > > > 
> > > > 
> > > > 你给的代码
> > > > ```makefile
> > > > run_hd:
> > > > 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -boot a -m 512
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > -device ahci 这不就是ahci吗
> > > 
> > > 
> > > makefile 改成这个样子了：
> > > ```makefile
> > > run:
> > > 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -device floppy -fda ./img/Powerint_DOS_386.img -drive id=disk,file=disk.img,if=none -device ide-hd,drive=disk -boot a -m 512
> > > run_hd:
> > > 	qemu-system-i386 -d in_asm -no-reboot -net nic,model=pcnet -net user -serial stdio -device sb16 -drive id=disk,file=disk.img,if=none -device ide-hd,drive=disk -boot a -m 512
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 该卡还得卡 最主要的是要弄明白 0x2a908b 到底是什么函数
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/86399932/327065864-605a9d32-e078-4377-a5a4-2dc056f0e5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDU5NTIsIm5iZiI6MTcxNDU0NTY1MiwicGF0aCI6Ii84NjM5OTkzMi8zMjcwNjU4NjQtNjA1YTlkMzItZTA3OC00Mzc3LWE1YTQtMmRjMDU2ZjBlNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA2NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYTk2OGUwYjkzNzE0MjhlN2RmZDEyZWU2NmMyZmY1Njk5OTQ1NWZmNWNhNjhhZDgwY2ZiNTgzYWFlOWFhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y8FVkUSCZ3bxI37gfERaQdY1U8ZLNM62aqocYGk-T-I) 我不认为是这个函数
> 
> 这个函数被调用 且只被调用一次

不止一次啊

```
Servicing hardware INT=0x20
----------------
IN:
0x002aaa20:  push   %ebx
0x002aaa21:  sub    $0x88,%esp
0x002aaa27:  nop
0x002aaa28:  call   0x2a908b

----------------
IN:
0x002aaa2d:  mov    0xed(%eax),%eax
0x002aaa33:  test   %eax,%eax
0x002aaa35:  je     0x2aaa28

----------------
IN:
0x002aaa28:  call   0x2a908b
```

```
----------------
IN:
0x002ab52b:  add    $0x10,%esp
0x002ab52e:  call   0x2a908b
```

```
----------------
IN:
0x002ab466:  add    $0x10,%esp
0x002ab469:  mov    %eax,0x1c(%esp)
0x002ab46d:  call   0x2a908b

----------------
IN:
0x002ab472:  mov    0x28(%eax),%edx
0x002ab475:  mov    0x1c(%esp),%eax
0x002ab479:  mov    %edx,0x28(%eax)
0x002ab47c:  mov    0x1c(%esp),%eax
0x002ab480:  movb   $0x1,0x175(%eax)
0x002ab487:  call   0x2a908b

----------------
IN:
0x002ab48c:  mov    0x171(%eax),%eax
0x002ab492:  mov    %eax,0x18(%esp)
0x002ab496:  call   0x2a908b

----------------
IN:
0x002ab49b:  movl   $0x0,0x171(%eax)
0x002ab4a5:  mov    0x1c(%esp),%eax
0x002ab4a9:  movl   $0x1,0x171(%eax)
0x002ab4b3:  movl   $0x1,0x2f2c10
0x002ab4bd:  call   0x2a908b

----------------
IN:
0x002ab4c2:  mov    0x30(%eax),%edx
0x002ab4c5:  mov    0x2c(%eax),%eax
0x002ab4c8:  mov    0x1c(%esp),%ecx
0x002ab4cc:  mov    %eax,0x34(%ecx)
0x002ab4cf:  mov    %edx,0x38(%ecx)
0x002ab4d2:  call   0x2a908b

----------------
IN:
0x002ab4d7:  mov    0x4c(%eax),%eax
0x002ab4da:  mov    %eax,0x14(%esp)
0x002ab4de:  call   0x2a908b

----------------
IN:
0x002ab4e3:  mov    0x4c(%eax),%edx
0x002ab4e6:  mov    0x1c(%esp),%eax
0x002ab4ea:  mov    %edx,0x4c(%eax)
0x002ab4ed:  call   0x2a908b
```

**Comment by min0911Y** [comment]
那应该是我这里编译的符号不同 我猜大概是current_task

**Comment by ghost** [comment]
[img.zip](https://github.com/min0911Y/Plant-OS/files/15174536/img.zip)

**Comment by min0911Y** [comment]
但你这个问题我还是没能复现
要不我现在交个commit你再编译一下

**Comment by ghost** [comment]
这是我编译的版本

**Comment by min0911Y** [comment]
更新了

**Comment by ghost** [comment]
> 更新了

仍有问题
卡在这：
```
----------------
IN:
0x002aab69:  call   0x2a91cc
```

**Comment by min0911Y** [comment]
> > 更新了
> 
> 仍有问题 卡在这：
> 
> ```
> ----------------
> IN:
> 0x002aab69:  call   0x2a91cc
> ```
我测试都没问题 你到底怎么触发的 详细讲一下

**Comment by ghost** [comment]
就是编译好之后运行啊

**Comment by ghost** [comment]
这是概率问题

**Comment by ghost** [comment]
有 20% ~ 40% 的概率

**Comment by ghost** [comment]
就很奇怪

**Comment by min0911Y** [comment]
> 就很奇怪

。。。。我这边完全不会有这个问题 初步怀疑是你qemu的问题

我的qemu版本是
![image](https://github.com/min0911Y/Plant-OS/assets/86399932/03f84a51-7170-4e94-8120-508f38132219)

**Comment by ghost** [comment]
QEMU emulator version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.17)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

**Comment by ghost** [comment]
一样的

**Comment by ghost** [comment]
连 Vmware 都会有这个问题

**Comment by min0911Y** [comment]
我完全测试不出来、、、

**Comment by min0911Y** [comment]
gcc版本？

**Comment by ghost** [comment]
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```

**Comment by min0911Y** [comment]
试试升级到gcc13再编译

**Comment by ghost** [comment]
您不能每更新一个版本就附带一个镜像吗？

**Comment by min0911Y** [comment]
> 您不能每更新一个版本就附带一个镜像吗？

这是代码仓库啊，肯定不放镜像

**Comment by ghost** [comment]
Releases!

**Comment by min0911Y** [comment]
> Releases!

我这一个版本都没结束我干啥releases

**Comment by min0911Y** [comment]
bug这么多我干啥要发releases

**Comment by ghost** [comment]
releases可以发测试版的啊
只需要点一个复选框就可以了

**Comment by min0911Y** [comment]
> releases可以发测试版的啊 只需要点一个复选框就可以了

那我现在连测试版都没开发完啊 没必要一个commit一个镜像

**Comment by ghost** [comment]
……

**Comment by min0911Y** [comment]
> ……

再说了  **您**遇到问题是一码事，遇到问题怎么能稳定复现是一码事 这和我**提不提供镜像**没啥关系

我每次处理**您**的issue都是看到你遇到bug不说咋复现

**您**需要有一个能够稳定复现的方法发给我 不是一句概率性问题让我在风中独自凌乱，如果这个概率是稳定触发 比如三次一下 两次一下 那我还能修，完全随机的概率**您**让我修个鬼啊

我怎么知道**您**干了啥导致的问题

**Comment by ghost** [comment]
> > ……
> 
> 再说了 **您**遇到问题是一码事，遇到问题怎么能稳定复现是一码事 这和我**提不提供镜像**没啥关系
> 
> 我每次处理**您**的issue都是看到你遇到bug不说咋复现
> 
> **您**需要有一个能够稳定复现的方法发给我 不是一句概率性问题让我在风中独自凌乱，如果这个概率是稳定触发 比如三次一下 两次一下 那我还能修，完全随机的概率**您**让我修个鬼啊
> 
> 我怎么知道**您**干了啥导致的问题

我就只是编译好了之后用 make run 运行啊！
我除此之外什么都没有干！

**Comment by ghost** [comment]
我怎么知道是什么 bug？

**Comment by ghost** [comment]
> > ……
> 
> 再说了 **您**遇到问题是一码事，遇到问题怎么能稳定复现是一码事 这和我**提不提供镜像**没啥关系
> 
> 我每次处理**您**的issue都是看到你遇到bug不说咋复现
> 
> **您**需要有一个能够稳定复现的方法发给我 不是一句概率性问题让我在风中独自凌乱，如果这个概率是稳定触发 比如三次一下 两次一下 那我还能修，完全随机的概率**您**让我修个鬼啊
> 
> 我怎么知道**您**干了啥导致的问题

刚启动就出 Bug 让我如何稳定复现？
请**您**给我说说如何在不给每一行代码打断点的情况下复现？

**Comment by min0911Y** [comment]
> > > ……
> > 
> > 
> > 再说了 **您**遇到问题是一码事，遇到问题怎么能稳定复现是一码事 这和我**提不提供镜像**没啥关系
> > 我每次处理**您**的issue都是看到你遇到bug不说咋复现
> > **您**需要有一个能够稳定复现的方法发给我 不是一句概率性问题让我在风中独自凌乱，如果这个概率是稳定触发 比如三次一下 两次一下 那我还能修，完全随机的概率**您**让我修个鬼啊
> > 我怎么知道**您**干了啥导致的问题
> 
> 刚启动就出 Bug 让我如何稳定复现？ 请**您**给我说说如何在不给每一行代码打断点的情况下复现？

于是乎你觉得我能解决这个你不能稳定复现的问题= =
于是乎你觉得我什么bug只要你说有bug我一定能找到 = =
是这样吗= =
如果不是，你就要给我足够的信息让我找bug 而不是让我大海捞针 懂吗！！！！

**Comment by ghost** [comment]
所以**您**让我大海捞针，是吗？！

**Comment by min0911Y** [comment]
> > > ……
> > 
> > 
> > 再说了 **您**遇到问题是一码事，遇到问题怎么能稳定复现是一码事 这和我**提不提供镜像**没啥关系
> > 我每次处理**您**的issue都是看到你遇到bug不说咋复现
> > **您**需要有一个能够稳定复现的方法发给我 不是一句概率性问题让我在风中独自凌乱，如果这个概率是稳定触发 比如三次一下 两次一下 那我还能修，完全随机的概率**您**让我修个鬼啊
> > 我怎么知道**您**干了啥导致的问题
> 
> 刚启动就出 Bug 让我如何稳定复现？ 请**您**给我说说如何在不给每一行代码打断点的情况下复现？

好了 我也不想和你说了  每次过来就一口一个您 还加粗，那我觉得就已经没什么好说的了 不要觉得每个开发者都是ChatGPT 会心平气和的陪你复现你遇到的奇怪的问题
忠告：
1. 我们不是朋友，我没有耐心和你玩找bug的游戏
2. 阴阳怪气不是解决问题的办法
3. 换位思考，你不知道bug是什么，我也不知道，你又不告诉bug怎么复现，我怎么找，这是issue，不是售后与客服界面，能理解吗？我们是一个平等的关系，你需要我做一件事情，就要给我能解决这件事情对等的信息，能否理解？你又没给我钱，你要给我钱了我当然可以耗尽心力陪你”这样不行怎么办“，我甚至还能帮你远程。首先你没给我带来任何利益，然后你还要对我做的事情评头论足，如果你觉得你写这个issue甚至是在帮助我，我应该感谢你的话，那还是谢绝了吧。
4. 送给你一句话：**We want to help you, but you need to help us help you** 相信你一定会用到的。

**Comment by min0911Y** [comment]
> 所以**您**让我大海捞针，是吗？！

我可以给你半个小时的时间思考一下我说的，再回忆一下你做的

平心而论，你能明确提出来bug的 我能复现 但我还没修的 我都没有CLOSE 提出来我能复现的我都fix了

**但是占比为什么这么少呢** 这个你就要自己思考思考了

**Comment by ghost** [comment]
那么请**您**告诉我，虚拟机**刚开机**就卡死的问题，我能给您提供什么信息？

**Comment by min0911Y** [comment]
> 那么请**您**告诉我，虚拟机**刚开机**就卡死的问题，我能给您提供什么信息？

那就是你的问题了，既然你没办法 我也没办法

**Comment by ghost** [comment]
而且不止 qemu，还有 Vmware，还有 VM VirtualBox 都有这种问题。
如果仅仅是其中一个，我姑且认为是虚拟机的问题。
那三个都有呢？
难道我还要再去用 bochs，PCem运行吗？

**Comment by min0911Y** [comment]
> 那么请**您**告诉我，虚拟机**刚开机**就卡死的问题，我能给您提供什么信息？

如你所见 我的虚拟机并不会**刚开机就卡死**

**Comment by min0911Y** [comment]
> 而且不止 qemu，还有 Vmware，还有 VM VirtualBox 都有这种问题。 如果仅仅是其中一个，我姑且认为是虚拟机的问题。 那三个都有呢？ 难道我还要再去用 bochs，PCem运行吗？

你没有给我复现的方法我怎么去修这个bug 你需要理解这一点 而不是情绪输出

**Comment by min0911Y** [comment]
> > 而且不止 qemu，还有 Vmware，还有 VM VirtualBox 都有这种问题。 如果仅仅是其中一个，我姑且认为是虚拟机的问题。 那三个都有呢？ 难道我还要再去用 bochs，PCem运行吗？
> 
> 你没有给我复现的方法我怎么去修这个bug 你需要理解这一点 而不是情绪输出

你只说了编译运行 这不是正常流程吗 我能commit上来肯定不会开机卡死

**Comment by min0911Y** [comment]
> > > 而且不止 qemu，还有 Vmware，还有 VM VirtualBox 都有这种问题。 如果仅仅是其中一个，我姑且认为是虚拟机的问题。 那三个都有呢？ 难道我还要再去用 bochs，PCem运行吗？
> > 
> > 
> > 你没有给我复现的方法我怎么去修这个bug 你需要理解这一点 而不是情绪输出
> 
> 你只说了编译运行 这不是正常流程吗 我能commit上来肯定不会开机卡死

至少**我这里不会**

**Comment by min0911Y** [comment]
> 而且不止 qemu，还有 Vmware，还有 VM VirtualBox 都有这种问题。 如果仅仅是其中一个，我姑且认为是虚拟机的问题。 那三个都有呢？ 难道我还要再去用 bochs，PCem运行吗？

我是真的累了 放五一我不想和你吵了 你自己好好想想吧
