### ISSUE TITLE
[BUG] 无法在 Oracle VM VirtualBox 下运行

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#3]
如这张图，Plant OS 在 Oracle VM VirtualBox v7.0.14 下以安装盘启动时，加载到此处直接卡死，无法运行
![VirtualBox_Plant OS 0 8x_09_03_2024_19_57_37](https://github.com/min0911Y/Plant-OS/assets/139534620/e7e11adb-b0f3-4c0f-a81d-b366129c610f)

**Comment by min0911Y** [comment]
VBOX要看情况 VBOX在我的intel机器上可以正常 但是在AMD会卡在init ide 去掉ide驱动的初始化也能正常


我认为你的情况是没给够内存 尝试2048MB内存

**Comment by ghost** [comment]
> VBOX要看情况 VBOX在我的intel机器上可以正常 但是在AMD会卡在init ide 去掉ide驱动的初始化也能正常
> 
> 我认为你的情况是没给够内存 尝试2048MB内存

内存给够了，版本是最新的，卡在了 AHCI 初始化。
![屏幕截图 2024-03-10 085416](https://github.com/min0911Y/Plant-OS/assets/139534620/5296c267-3ced-4c2a-afa7-59c89bff3dbe)

**Comment by min0911Y** [comment]
试一下去掉ahci设备和ide设备

**Comment by ghost** [comment]
> 试一下去掉ahci设备和ide设备

其实也没有这个必要，毕竟我只是想要试用一下，Vmware 上是能用的
