### ISSUE TITLE
[BUG] 安装程序光标位置不正确，容易误导使用者

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#4]
如图，安装程序选中了“OK”，但是光标竟然在“Cancel”处
![屏幕截图 2024-03-09 203303](https://github.com/min0911Y/Plant-OS/assets/139534620/b8c4a3b1-4128-44ab-94e0-114825dd3170)

**Comment by min0911Y** [comment]
你按两下左右键不久知道红色是选中了。。。

**Comment by ghost** [comment]
> 你按两下左右键不久知道红色是选中了。。。

可是要面对普通用户需要一目了然啊

**Comment by min0911Y** [comment]
我就算没有这个光标你就知道红色代表选中了？如果你想改其实可以提PR的  这个东西我认为没啥必要
