### ISSUE TITLE
[BUG] 软盘更换后必须要重启才能更新目录

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#7]
如题，当插入安装盘之后，访问 A 盘，切回 C 盘，更换为 TCC 盘，再次切到 A 盘，dir 出来的仍然是安装盘的文件。

**Comment by min0911Y** [comment]
你需要使用rdrv 命令

**Comment by ghost** [comment]
> 你需要使用rdrv 命令

不能自动吗？

**Comment by min0911Y** [comment]
假如我没有切换软盘  那么是否每次都要等待一下？不麻烦吗

**Comment by ghost** [comment]
> 假如我没有切换软盘 那么是否每次都要等待一下？不麻烦吗

重要的问题在于，使用 "A:" 并不能直接访问新的软盘

**Comment by min0911Y** [comment]
是的，你需要使用rdrv，我讲的很清楚了

**Comment by min0911Y** [comment]
如果你真的需要这项功能，请修改apps/psh的源码

**Comment by ghost** [comment]
> 如果你真的需要这项功能，请修改apps/psh的源码

这样还不如自己写一个操作系统啊

**Comment by ghost** [comment]
> 如果你真的需要这项功能，请修改apps/psh的源码

而且这么多的 API 竟然没有一点文档

**Comment by min0911Y** [comment]
“这样还不如自己写一个操作系统啊” 改个shell啊哥儿

**Comment by min0911Y** [comment]
> > 如果你真的需要这项功能，请修改apps/psh的源码
> 
> 而且这么多的 API 竟然没有一点文档

之后吧， 有时间会搞的。目前学业为重，能开发就不错了，文档没啥时间整

**Comment by ghost** [comment]
> “这样还不如自己写一个操作系统啊” 改个shell啊哥儿

面对着一堆风格迥异，函数命名英文拼音混杂的代码，我怎么下手啊？

**Comment by ghost** [comment]
> > > 如果你真的需要这项功能，请修改apps/psh的源码
> > 
> > 
> > 而且这么多的 API 竟然没有一点文档
> 
> 之后吧， 有时间会搞的。目前学业为重，能开发就不错了，文档没啥时间整

难道我不是初中学生吗？

**Comment by min0911Y** [comment]
好好好 我承认风格迥异，请问哪里有拼音

**Comment by min0911Y** [comment]
这是切盘
```c
else if (line[1] == ':' && line[2] == '\0') {
    if (!vfs_check_mount(line[0])) {
      if (!vfs_mount(line[0], line[0])) {
        printf("disk not ready!\n");
      } else {
        vfs_change_disk(line[0]);
      }
    } else {
      vfs_change_disk(line[0]);
    }
  }
```
  obviously，删掉vfs_check_mount(line[0])即可
  作为一个能上github的初中学生，check会吧？mount见过吧
  就算chinglish check mount不会不知道啥意思
  
 psh本身就没有很复杂，又没有叫你去改内核，你想你可以重写一个psh
 
而且你并没有说出使用"A:"直接访问软盘的必要性

**Comment by min0911Y** [comment]
你跟我说切不了盘 我告诉你怎样切，这个issue就已经终结了哥儿
