### ISSUE TITLE
[BUG] tcc 安装卡死

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#8]
如图，TCC 在安装到复制 tcc/lib/libp.a 时卡死
![屏幕截图 2024-03-09 212343](https://github.com/min0911Y/Plant-OS/assets/139534620/8a414d2a-f47f-4837-8c90-c2f92571b0ef)

**Comment by min0911Y** [comment]
没复现出来 如果用AHCI驱动器 那请不要使用AHCI驱动器安装 还有bug
（一并回复 Editor 测试）
![{CBCDC447-F877-4b3f-9D19-C2EC0D40D9C5}](https://github.com/min0911Y/Plant-OS/assets/86399932/7fe78a39-aec8-4bf2-8443-b17c035e651a)

（tcc）

![{D9E4288F-6B44-4cce-841F-40A696703D4F}](https://github.com/min0911Y/Plant-OS/assets/86399932/a91989fe-964f-45df-8a7c-ddc01a37f0cf)
![image](https://github.com/min0911Y/Plant-OS/assets/86399932/e1bfc61b-10f2-417a-8a29-5d9639cc43a1)
（软盘切换）
![image](https://github.com/min0911Y/Plant-OS/assets/86399932/514d5117-ed17-40ee-b16d-d7899e5760df)


无一复现，重新编译 或者等我提交新版本或能解决问题
