### ISSUE TITLE
[BUG] Color 命令会清除部分文本的属性

### ISSUE THREAD

**Issue by ghost** [min0911Y/Plant-OS#9]
如图，设置了 Color 07 以后原本的绿色文本统统全黑
![屏幕截图 2024-03-09 214234](https://github.com/min0911Y/Plant-OS/assets/139534620/48579ebf-0402-4762-b312-37791663a3c9)

**Comment by min0911Y** [comment]
这是正常的，如果要记录颜色信息，那么需要耗费一些内存，牺牲效率，我不想这么做

**Comment by ghost** [comment]
> 这是正常的，如果要记录颜色信息，那么需要耗费一些内存，牺牲效率，我不想这么做

不是啊，0xB8000 往后不是一个字节存储颜色，一个字节存储文本吗？

**Comment by min0911Y** [comment]
原因很简单，我不认为这是个bug，我的设计就是这样，而且哥儿我问你，什么时候我们应该不改变这个颜色呢？那我是不是还得再搞片内存标记这个地方是不是改过？
